steps:
  - name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cloning the Spring Models repository..."
        git clone https://nahushr18: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@github.com/nahushr18/SpringModels.git
        echo "Switching to the development branch..."
        cd SpringModels
        git checkout development
        echo "Building the Spring Models project..."
        mvn clean install
        cd ../
        echo "Changing to the SpringApi directory..."
        cd SpringApi
        echo "Building the application..."
        mvn clean install

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/ultimate-company/spring-api', '.'
    ]
    dir: SpringApi
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'spring-api', '--image', 'gcr.io/ultimate-company/spring-api', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
timeout: '1200s'
options:
  machineType: 'N1_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'
